language: go

sudo: false

go:
  - 1.7.x

before_install:
  - go get github.com/mattn/goveralls

script:
- go test -covermode=count -coverprofile=profile.cov
- $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
